services:
  tor:
    image: dockurr/tor:latest
    container_name: tor_proxy
    networks:
      - lbrowser_net
    ports:
      - "127.0.0.1:9050:9050"
    volumes:
      - tor_data:/var/lib/tor
    restart: unless-stopped

  zeronet:
    image: canewsin/zeronet:latest
    container_name: zeronet_node
    networks:
      - lbrowser_net
    ports:
      - "127.0.0.1:43111:43110"
    volumes:
        - zeronet_data:/root/data
    restart: unless-stopped

  i2p:
    image: geti2p/i2p:latest
    container_name: i2p_node
    networks:
      - lbrowser_net
    ports:
      - "127.0.0.1:4444:4444"   # HTTP Proxy
      - "127.0.0.1:7654:7654"   # I2CP Protocol
      - "127.0.0.1:7657:7657"   # Router console
      - "12345:12345/tcp"       # I2NP Protocol TCP
      - "12345:12345/udp"       # I2NP Protocol UDP
    volumes:
      - i2p_config:/i2p/.i2p
      - i2p_torrents:/i2psnark
    restart: unless-stopped

  freenet:
    image: poullorca/hyphanet-node:latest
    container_name: hyphanet_node
    networks:
      - lbrowser_net
    ports:
      - "127.0.0.1:8889:8888"
    volumes:
      - hyphanet_data:/data
    restart: unless-stopped

volumes:
  tor_data:
  zeronet_data:
  hyphanet_data:
  i2p_config:
  i2p_torrents:

networks:
  lbrowser_net:
    driver: bridge